### ISSUE TITLE
FTP Uploading Export-File

### ISSUE THREAD

**Issue by exc-peter** [FACT-Finder-Web-Components/shopware5-plugin#63]
- FACT-Finder plugin version: 2.0.1
- Shopware version: 5.6.2
- PHP version: 7.2.33

**Uploading Export file not possible**

Error in SW5 Backend:
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The "shop" service is synthetic, it needs to be set at boot time before it can be used. in /www/vendor/symfony/dependency-injection/Container.php:334 Stack trace: #0 /www/engine/Shopware/Components/DependencyInjection/Container.php(218): Symfony\Component\DependencyInjection\Container->get('shop', 1) #1 /www/engine/Shopware/Components/DependencyInjection/Container.php(140): Shopware\Components\DependencyInjection\Container->doLoad('shop', 'shop', 1) #2 /www/var/cache/production_201909250854/proxies/ShopwareProduction3cc3517b34506254f1e9471efd606165724a3dd9ProjectContainer.php(4863): Shopware\Components\DependencyInjection\Container->get('shop') #3 /www/vendor/symfony/dependency-injection/Container.php(306): ShopwareProduction3cc3517b34506254f1e9471efd606165724a3dd9ProjectCont in /www/vendor/symfony/dependency-injection/Container.php on line 334

Also does the "-u" Option not work in the console

- Steps to reproduce:  Go to plugin settings > Click to "Check credentials" regarding FTP

**Comment by a-laurowski** [comment]
Hi @exc-peter
Can i ask you to provide us an information where `shop` service is specified or referenced as a service in shopware5 codebase?

I was unable to reproduce the error, nor did I find any instances of of binding such a service to any of service the plugin is providing.

**Comment by a-laurowski** [comment]
@exc-peter I'm closing this issue due to inactivity. Feel free to reopen if necessary
